// Generated by gencpp from file kdlidar_ros_msgs/SaveMap.msg
// DO NOT EDIT!


#ifndef KDLIDAR_ROS_MSGS_MESSAGE_SAVEMAP_H
#define KDLIDAR_ROS_MSGS_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <kdlidar_ros_msgs/SaveMapRequest.h>
#include <kdlidar_ros_msgs/SaveMapResponse.h>


namespace kdlidar_ros_msgs
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace kdlidar_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kdlidar_ros_msgs::SaveMap > {
  static const char* value()
  {
    return "d08a3b641c2f8680fbdfb1ea2e17a3e1";
  }

  static const char* value(const ::kdlidar_ros_msgs::SaveMap&) { return value(); }
};

template<>
struct DataType< ::kdlidar_ros_msgs::SaveMap > {
  static const char* value()
  {
    return "kdlidar_ros_msgs/SaveMap";
  }

  static const char* value(const ::kdlidar_ros_msgs::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::kdlidar_ros_msgs::SaveMapRequest> should match
// service_traits::MD5Sum< ::kdlidar_ros_msgs::SaveMap >
template<>
struct MD5Sum< ::kdlidar_ros_msgs::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kdlidar_ros_msgs::SaveMap >::value();
  }
  static const char* value(const ::kdlidar_ros_msgs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kdlidar_ros_msgs::SaveMapRequest> should match
// service_traits::DataType< ::kdlidar_ros_msgs::SaveMap >
template<>
struct DataType< ::kdlidar_ros_msgs::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::kdlidar_ros_msgs::SaveMap >::value();
  }
  static const char* value(const ::kdlidar_ros_msgs::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kdlidar_ros_msgs::SaveMapResponse> should match
// service_traits::MD5Sum< ::kdlidar_ros_msgs::SaveMap >
template<>
struct MD5Sum< ::kdlidar_ros_msgs::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kdlidar_ros_msgs::SaveMap >::value();
  }
  static const char* value(const ::kdlidar_ros_msgs::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kdlidar_ros_msgs::SaveMapResponse> should match
// service_traits::DataType< ::kdlidar_ros_msgs::SaveMap >
template<>
struct DataType< ::kdlidar_ros_msgs::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::kdlidar_ros_msgs::SaveMap >::value();
  }
  static const char* value(const ::kdlidar_ros_msgs::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KDLIDAR_ROS_MSGS_MESSAGE_SAVEMAP_H
