// Generated by gencpp from file kdlidar_ros_msgs/TrackingState.msg
// DO NOT EDIT!


#ifndef KDLIDAR_ROS_MSGS_MESSAGE_TRACKINGSTATE_H
#define KDLIDAR_ROS_MSGS_MESSAGE_TRACKINGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace kdlidar_ros_msgs
{
template <class ContainerAllocator>
struct TrackingState_
{
  typedef TrackingState_<ContainerAllocator> Type;

  TrackingState_()
    : header()
    , tracking_state(0)
    , msg()  {
    }
  TrackingState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tracking_state(0)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _tracking_state_type;
  _tracking_state_type tracking_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INITIALISING)
  #undef INITIALISING
#endif
#if defined(_WIN32) && defined(TRACKING)
  #undef TRACKING
#endif
#if defined(_WIN32) && defined(LOST)
  #undef LOST
#endif

  enum {
    INITIALISING = 1u,
    TRACKING = 2u,
    LOST = 3u,
  };


  typedef boost::shared_ptr< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> const> ConstPtr;

}; // struct TrackingState_

typedef ::kdlidar_ros_msgs::TrackingState_<std::allocator<void> > TrackingState;

typedef boost::shared_ptr< ::kdlidar_ros_msgs::TrackingState > TrackingStatePtr;
typedef boost::shared_ptr< ::kdlidar_ros_msgs::TrackingState const> TrackingStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator1> & lhs, const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tracking_state == rhs.tracking_state &&
    lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator1> & lhs, const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kdlidar_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24ce8050df75d306a134249a22b4b324";
  }

  static const char* value(const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24ce8050df75d306ULL;
  static const uint64_t static_value2 = 0xa134249a22b4b324ULL;
};

template<class ContainerAllocator>
struct DataType< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kdlidar_ros_msgs/TrackingState";
  }

  static const char* value(const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Tracking state from kdlidar\n"
"\n"
"# System is currently initialising / in need of initialisation\n"
"uint8 INITIALISING = 1\n"
"# Tracking is happening\n"
"uint8 TRACKING = 2\n"
"# Tracking is lost - relocalisation required\n"
"uint8 LOST = 3\n"
"\n"
"\n"
"Header header\n"
"uint8 tracking_state\n"
"string msg\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tracking_state);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackingState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kdlidar_ros_msgs::TrackingState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tracking_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tracking_state);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KDLIDAR_ROS_MSGS_MESSAGE_TRACKINGSTATE_H
