kdlidar_ros_pcl:

  # Parameters
  publish_pointcloud: true
  publish_pose: true
  reset_map: false
  
  # Map loading
  load_map: false
  map_file: ""

  # Frames
  pointcloud_frame_id: "map"
  camera_frame_id: "camera_link"

  lidarSettings:
    trackingOnlyMode: false
    optimiseGraphAutomatically: true
    shouldDetectLoops: false

    # Lidar type
    trackingVoxelSize: 1.0
    maxMatchDistanceFrameToFrame: 4.0
    maxMatchDistanceFrameToMap: 1.0
    # IMU
    undistortWithImu: true

    # GPS
    minNumKeyFramesToAlignGps: 5
    defaultGpsWeight: 100.0
    gpsAlignmentPercentage: 1.0
    localOptimisationWindowSize: 10
    gpsAssociationTimeout: 1

    # Dense map
    storeAllFrames: false

  # GPS mode
  use_gps: true
  # Extrinsics from GPS to Lidar
  gps_to_lidar_rot: [9.999976e-01,7.553071e-04,-2.035826e-03,-7.854027e-04,9.998898e-01,-1.482298e-02,2.024406e-03,1.482454e-02,9.998881e-01]
  gps_to_lidar_tran: [-8.086759e-01,3.195559e-01,-7.997231e-01]

  # IMU mode
  use_imu: true
  # Extrinsics from IMU to Lidar
  imu_to_lidar_rot: [9.999976e-01,7.553071e-04,-2.035826e-03,-7.854027e-04,9.998898e-01,-1.482298e-02,2.024406e-03,1.482454e-02,9.998881e-01]
  imu_to_lidar_tran: [-8.086759e-01,3.195559e-01,-7.997231e-01]
